# docker compose version is 3.7 (may work for less, but only tested with 3.7)
version: "3.7"
services:
  web:
    # docker build context is the current directory
    build:
      context: .
      args:
        - DATABASE=${DATABASE}
        - GROUP_ID=${GROUP_ID}
        - USER_ID=${USER_ID}
    # tag the image after it's built
    #        app / app version : docker image version (per app version)
    image: alexandrie-0.1.0-${DATABASE}:0.1
    deploy:
      replicas: 1
    # grab these from the .env file
    restart: always
    environment:
      CRATE_INDEX: $CRATE_INDEX
      DATABASE: $DATABASE
      GIT_NAME: $GIT_NAME
      GIT_EMAIL: $GIT_EMAIL
    ports:
      - "3000:3000"
    volumes:
      - ${APPDATA}:/home/alex/appdata
      - ./docker/${DATABASE}/alexandrie.toml:/home/alex/alexandrie.toml
      - ${GIT_SSH_KEY}:/home/alex/.ssh/id_rsa
